name: tree-list

version: 0.1.0.0

ghc-options: -Wall

dependencies:
  - base
  - classy-prelude
  - optparse-generic
  - containers >= 0.2
  - mono-traversable
  - ordered-containers

default-extensions:
  - NoImplicitPrelude
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies
  - TypeApplications
  - TypeOperators
  - QuantifiedConstraints

library:
  source-dirs: src/

executables:
  tree-list:
    main: Main.hs
    source-dirs: app/
    dependencies:
      - tree-list
